Puppet 6 Conversion Magic
rackerlabs/puppet-repose pull request #93
Opened 2021-03-02 16:37 UTC by cringdahl

2021-03-02 21:54 UTC, jstraw requested changes
Almost there!

2021-03-02 21:54 UTC, jstraw commented on spec/defines/filter/open_tracing_spec.rb
> +          should contain_file('/etc/repose/open-tracing.cfg.xml').with_content(/connection-http endpoint=\"http:\/\/example.com\/api\/traces\"/)
for the future, we should merge these with content like other tests instead of writing multiple it tests

2021-03-04 22:54 UTC, jstraw requested changes
waiting for one last changeset, resetting my last review for PR system

2021-03-05 15:06 UTC, cringdahl commented on spec/classes/config_spec.rb
> +      it { is_expected.to compile.with_all_deps }
check lines 10-20

2021-03-05 16:13 UTC, jstraw approved these changes

2021-03-08 21:45 UTC, jstraw approved these changes

2021-03-08 21:46 UTC, jstraw approved these changes

2021-03-08 23:28 UTC, jstraw commented
We'll put together a changelog/release later this week.  Merge in the AM

2021-03-09 15:20 UTC, merged